using global::System;
using global::System.Collections.Generic;
using global::System.Drawing;
using global::System.IO;
using global::System.Linq;
using global::System.Threading;
using global::System.Threading.Tasks;
using global::System.Windows.Forms;

namespace ZNK
{
    // GENERATED by gen.py from the decompiled handlers of the original Form2.
    // Statement order is exactly the original's. Do not edit; edit gen.py or
    // move a handler into GameForm.Hand.cs.in instead.
    sealed partial class GameForm
    {
        void WireEvents()
        {
            OnClick("absinth", absinth_Click);
            OnClick("Adolf", Adolf_Click);
            OnDragDrop("Adolf", Adolf_DragDrop);
            OnClick("adolfI", adolfI_Click);
            OnClick("armyshopGO", armyshopGO_Click);
            OnClick("atomovka", atomovka_Click);
            OnDragDrop("baterka", baterka_DragDrop);
            OnClick("batérky", batérky_Click);
            OnClick("Brokovnice", Brokovnice_Click);
            OnDragDrop("BrokovniceI", BrokovniceI_DragDrop);
            OnClick("číšník", číšník_Click);
            OnDragDrop("číšník", číšník_DragDrop);
            OnClick("číšníkubodán", číšníkubodán_Click);
            OnClick("doložnice", doložnice_Click);
            OnClick("doROOM", doROOM_Click);
            OnClick("Douličky", Douličky_Click);
            OnClick("dovnitř", dovnitř_Click);
            OnClick("důmGO", důmGO_Click);
            OnClick("Dveře", Dveře_Click);
            OnClick("Fidel", Fidel_Click);
            OnDragDrop("Fidel", Fidel_DragDrop);
            OnClick("fidelI", fidelI_Click);
            OnClick("help", help_Click);
            OnClick("hospodaGO", hospodaGO_Click);
            OnClick("icp", icp_Click);
            OnClick("Image1", Image1_Click);
            OnClick("Image10", Image10_Click);
            OnClick("Image11", Image11_Click);
            OnDragDrop("Image11", Image11_DragDrop);
            OnClick("Image12", Image12_Click);
            OnClick("Image13", Image13_Click);
            OnClick("Image14", Image14_Click);
            OnClick("Image15", Image15_Click);
            OnClick("Image16", Image16_Click);
            OnClick("Image17", Image17_Click);
            OnClick("Image18", Image18_Click);
            OnClick("Image19", Image19_Click);
            OnClick("Image2", Image2_Click);
            OnClick("Image3", Image3_Click);
            OnClick("Image4", Image4_Click);
            OnClick("Image5", Image5_Click);
            OnClick("Image6", Image6_Click);
            OnClick("Image7", Image7_Click);
            OnDragDrop("Image7", Image7_DragDrop);
            OnClick("Image8", Image8_Click);
            OnClick("Image9", Image9_Click);
            OnClick("Josef", Josef_Click);
            OnDragDrop("Josef", Josef_DragDrop);
            OnClick("josefI", josefI_Click);
            OnClick("kamen", kamen_Click);
            OnDragDrop("kamen", kamen_DragDrop);
            OnClick("kameros", kameros_Click);
            OnDragDrop("kameros", kameros_DragDrop);
            OnClick("kleště", kleště_Click);
            OnClick("Koberec", Koberec_Click);
            OnClick("konec", konec_Click);
            OnClick("kpoklopu", kpoklopu_Click);
            OnClick("kufr", kufr_Click);
            OnClick("Label1", Label1_Click);
            OnClick("láhev", láhev_Click);
            OnDblClick("lahev", lahev_DblClick);
            OnClick("leave", leave_Click);
            OnClick("nápis", nápis_Click);
            OnClick("obchodGO", obchodGO_Click);
            OnClick("odejít", odejít_Click);
            OnClick("Okno", Okno_Click);
            OnClick("pas", pas_Click);
            OnClick("PenízeI", PenízeI_Click);
            OnDragDrop("PenízeI", PenízeI_DragDrop);
            OnClick("pistole", pistole_Click);
            OnDragDrop("pistoleI", pistoleI_DragDrop);
            OnClick("pivo", pivo_Click);
            OnClick("pláž", pláž_Click);
            OnClick("Poklop", Poklop_Click);
            OnDragDrop("Poklop", Poklop_DragDrop);
            OnClick("PoklopSPECIAL", PoklopSPECIAL_Click);
            OnClick("prodavač", prodavač_Click);
            OnDragDrop("prodavač", prodavač_DragDrop);
            OnClick("ProdavačDEATH", ProdavačDEATH_Click);
            OnClick("ProdavačLOOK", ProdavačLOOK_Click);
            OnDragDrop("ProdavačLOOK", ProdavačLOOK_DragDrop);
            OnClick("pryč", pryč_Click);
            OnClick("rukavice", rukavice_Click);
            OnClick("rukaviceI", rukaviceI_Click);
            OnClick("skrytoš", skrytoš_Click);
            OnDragDrop("skrytoš", skrytoš_DragDrop);
            OnClick("surmaj", surmaj_Click);
            OnClick("šéf", šéf_Click);
            OnDragDrop("šéf", šéf_DragDrop);
            OnClick("šéfGUN", šéfGUN_Click);
            OnClick("šéfSHOTGUN", šéfSHOTGUN_Click);
            OnClick("Tlačítko", Tlačítko_Click);
            OnClick("tma", tma_Click);
            OnDragDrop("tma", tma_DragDrop);
            OnClick("tulák", tulák_Click);
            OnDragDrop("tulák", tulák_DragDrop);
            OnClick("tulákubodán", tulákubodán_Click);
            OnClick("typ", typ_Click);
            OnDragDrop("typ", typ_DragDrop);
            OnClick("TypMRTVEJ", TypMRTVEJ_Click);
            OnClick("uliceGO", uliceGO_Click);
            OnClick("vejít", vejít_Click);
            OnClick("vesmír", vesmír_Click);
            OnClick("vobraZ", vobraZ_Click);
            OnClick("výbuch", výbuch_Click);
            OnClick("výloha", výloha_Click);
            OnDragDrop("výloha", výloha_DragDrop);
            OnClick("whiskey", whiskey_Click);
            OnClick("zápalky", zápalky_Click);
            OnClick("Žena", Žena_Click);
            OnDragDrop("Žena", Žena_DragDrop);
            OnClick("ženaGUN", ženaGUN_Click);
        }

        void Adolf_Click()
        {
            Say("Chtěl jsem sem dát největšího padoucha co kdy žil, ale neuměl jsem Santu nakreslit, tak jsem sem dal alespoň Adolfa Hitlera, to byl taky docela grázl");
        }

        void Adolf_DragDrop(Control src)
        {
            if (src == C("BrokovniceI") && f_46 == 3) { Hide("PoklopSPECIAL"); Show("Tlačítko"); }
            if (src == C("BrokovniceI") && f_46 == 2) { f_46 = 3; }
            if (src == C("BrokovniceI") && f_46 == 1) { f_46 = 2; }
            if (src == C("BrokovniceI") && f_46 == 0) { f_46 = 1; }
            if (src == C("BrokovniceI")) { snd = "Shoot.wav"; PlaySound(snd); Show("adolfI"); Say("Pěkně si toho parchanta vodrovnal! To mu patří!"); Hide("Adolf"); }
            if (src == C("pistoleI")) { Say("To na něj nestačí!"); }
            if (src == C("PistoleII")) { Say("To na něj nestačí!"); }
        }

        void adolfI_Click()
        {
            Say("To mu patří parchantovi!");
        }

        void armyshopGO_Click()
        {
            Show("Armyshop");
            Hide("mapa");
            Say("Vešel jsi do obchodu se zbraněmi, všude po stěnách visí zbraně a na pultu vidíš dokonce jadernou hlavici");
        }

        void baterka_DragDrop(Control src)
        {
            if (src == C("baterky")) { Say("Narval si baterky do baterky a hle! Fugnuje!"); Hide("baterky"); Tip("baterka", "Funkční Baterka"); f_3e = 1; }
        }

        void batérky_Click()
        {
            Hide("batérky");
            Show("baterky");
            Say("Sebral baterky");
        }

        void BrokovniceI_DragDrop(Control src)
        {
            if (src == C("tlumič")) { Say("Tlumič tam nepasuje a mimochodem, už si někdy viděl tlumič na brokovnici?"); }
        }

        void číšník_Click()
        {
            Say("ČÍŠNÍK: Co tady chceš? Buď si něco kup nebo vypadni! Na takový jako seš tu nejsem zvědavej!");
        }

        void číšník_DragDrop(Control src)
        {
            if (src == C("lahev")) { Show("číšníkubodán"); f_3a = 0; snd = "bum.wav"; PlaySound(snd); Say("Sice si parádně odrovnal toho grázla, ale v naplněným lokále to asi nebyl moc dobrej nápad"); Tip("pivo", "Sebrat pivo"); Tip("whiskey", "Sebrat whiskey"); Tip("absinth", "Sebrat absinth"); }
            if (src == C("baterky")) { Say("Di s těma baterkama do prdele!"); }
            if (src == C("baterka")) { Say("To nechci"); }
            if (src == C("pistoleI")) { Say("Rozhodl ses, že zbytečně nebudeš plýtvat střelivem"); }
            if (src == C("PistoleII")) { Say("Rozhodl ses, že zbytečně nebudeš plýtvat střelivem"); }
            if (src == C("BrokovniceI")) { Say("Rozhodl ses, že zbytečně nebudeš plýtvat střelivem"); }
            if (src == C("zápalkyI")) { Say("Ty zápalky si klidně nech"); }
            if (src == C("PivoI"))
            {
                Say("No, to je pivo co sis koupil. Tak si ho vypij a vypadni!");
            }
            if (src == C("whiskeyI")) { Say("Běž do píči a nech mě na pokoji!"); }
            if (src == C("absinthI")) { Say("Já ten absinth nechci! Koupil sis ho tak vypadni!"); }
            if (src == C("atomovkaI")) { Say("Helemese! Díky! Připravím ji k odpálení, chlapci jsou v zadní místnosti, běž za nima/ukazuje na dveře za ním"); Show("doROOM"); Hide("atomovkaI"); }
            if (src == C("KufrI")) { Say("Ten kufr je hnusnej"); }
            if (src == C("tlumič")) { Say("Strč si ten tlumič do prdele a už mě neser"); }
            if (src == C("klíč")) { Say("The Roof, The Roof, The Roof is on fire, we don´t need no water let the motherfucker burn, burn motherfucker"); }
        }

        void číšníkubodán_Click()
        {
            Say("Tak tohle je ubodanej číšník - odvedl jsi pěkně krutou práci");
        }

        void doložnice_Click()
        {
            Show("Ložnice");
            Hide("Uvnitř");
            Say("Vstoupil jsi k šéfikovi do ložnice...");
            if (V("skrytoš")) { f_42 = 2; }
        }

        void doROOM_Click()
        {
            Show("tajnámístnost");
            Hide("HospodaIN");
            Say("Vešel jsi do místnosti. K tvému úžasu se v ní skrývají největší padouchové světa! Fidel Kastro, Josef Stalin a Adolf Hitler. Všichni jsou však ve špatné náladě, musíš je nějak rozveselit a pak už můžete odpálit jadernou hlavici!");
        }

        void Douličky_Click()
        {
            Show("ulička");
            Hide("Obchod");
            Say("Přišel jsi slepé uličky");
        }

        void dovnitř_Click()
        {
            Show("obchodIN");
            Hide("Obchod");
            Say("Vešel jsi do obchodu, v regálech toho moc nemaj. Všimnul sis, že tě sleduje kamera");
        }

        void důmGO_Click()
        {
            Show("dům");
            Hide("mapa");
            Say("Stojíš před zdí, která obíhá celý komplex šéfova domu");
        }

        void Dveře_Click()
        {
            Hide("Dveře");
            if (!V("rukaviceI")) { f_40 = 2; }
            if (V("rukaviceI")) { f_40 = 1; }
            Say("No, tak nejsou tak zamčený jak vypadali... můžeš vejít");
        }

        void Fidel_Click()
        {
            Say(" Tak tohle je Fidel Kastro! Komoušskej kápo. Vypadá docela smutně");
        }

        void Fidel_DragDrop(Control src)
        {
            if (src == C("zápalkyI") && f_46 == 3) { Hide("PoklopSPECIAL"); Show("Tlačítko"); }
            if (src == C("zápalkyI") && f_46 == 2) { f_46 = 3; }
            if (src == C("zápalkyI") && f_46 == 1) { f_46 = 2; }
            if (src == C("zápalkyI") && f_46 == 0) { f_46 = 1; }
            if (src == C("zápalkyI")) { Show("fidelI"); Say("Ah, zapálil jsi mu doutníčka, teď už je spokojenej"); Hide("Fidel"); Hide("zápalky"); }
        }

        void fidelI_Click()
        {
            Say("Se zapálenym havanem vypadá šťastně");
        }

        void hospodaGO_Click()
        {
            Hide("mapa");
            Show("hospoda");
            Say("Stojíš před hospodou u dvou hlav");
        }

        void icp_Click()
        {
            Say("INSANE CLOWN POSSE - www.insaneclownposse.com, viva la juggalos, 6th joker´s card, Shangri-La");
        }

        void Image1_Click()
        {
            Say("Vyber si kam chceš jít");
            Hide("ulice");
            Show("mapa");
        }

        void Image10_Click()
        {
            Hide("Armyshop");
            Show("mapa");
            Say("Vyber si kam chceš jít, amígo!");
        }

        void Image11_Click()
        {
            Say("PRODAVAČ: Nazdar, já jsem bejvalej voják a teď mi patří krám, mám tu všechno. Dokonce i jadernou hlavici, ale s tou bacha... a na mě si dej taky bacha!");
        }

        void Image11_DragDrop(Control src)
        {
            if (src == C("lahev")) { Say("Vycítil tvojí agresivitu a než si stihnul cokoliv udělat, vytáhnul z podpultu čtyřiačtyřicítku a udělal ti do hlavy další otvor"); Hide("Armyshop"); Hide("inventář"); Hide("lahev"); }
            if (src == C("pistoleI")) { Say("Vycítil tvojí agresivitu a než si stihnul cokoliv udělat, vytáhnul z podpultu čtyřiačtyřicítku a udělal ti do hlavy další otvor"); Hide("Armyshop"); Hide("inventář"); Hide("lahev"); }
            if (src == C("BrokovniceI")) { Say("Vycítil tvojí agresivitu a než si stihnul cokoliv udělat, vytáhnul z podpultu čtyřiačtyřicítku a udělal ti do hlavy další otvor"); Hide("Armyshop"); Hide("inventář"); Hide("lahev"); }
            if (src == C("Kámen")) { Say("Vycítil tvojí agresivitu a než si stihnul cokoliv udělat, vytáhnul z podpultu čtyřiačtyřicítku a udělal ti do hlavy další otvor"); Hide("Armyshop"); Hide("inventář"); Hide("lahev"); }
            if (src == C("klíč")) { Say("You and me baby ain’t nothin’ but mammals, So let’s do it like they do on the Discovery Channel"); }
        }

        void Image12_Click()
        {
            Say("m.pohl@worldonline.cz");
        }

        void Image13_Click()
        {
            Hide("dům");
            Show("mapa");
            Say("Vyber si kam chceš jít");
        }

        void Image14_Click()
        {
            Show("vchod");
            Hide("dům");
            Say("Přelezl si zeď, stojíš před zamčenými dvěřmi");
        }

        void Image15_Click()
        {
            Hide("vchod");
            Show("policie");
            Hide("inventář");
            Hide("lahev");
            Say("Tak tohle byla největší píčovina jakou jsi mohl udělat. Zatkli tě za neoprávněné vniknutí na pozemek. Seš fakt kretén");
        }

        void Image16_Click()
        {
            Say("Vrátil ses zpět");
            Hide("Poklopec");
            Show("Uvnitř");
        }

        void Image17_Click()
        {
            Say("Šéfovi brejličky");
        }

        void Image18_Click()
        {
            Hide("Ložnice");
            Show("Uvnitř");
            Say("Vrátil ses");
        }

        void Image19_Click()
        {
            Show("HospodaIN");
            Hide("tajnámístnost");
            Say("Vrátil ses zpátky do lokálu");
        }

        void Image2_Click()
        {
            Say("http://northcrewz.zde.cz");
        }

        void Image3_Click()
        {
            Hide("hospoda");
            Show("mapa");
            Say("Vyber si kam chceš jít");
        }

        void Image4_Click()
        {
            Say("Vstoupil jsi do hospody, je to cejtit chcánkama a kouřem. Za pultem stojí obtloustlý, funící číšník - vypadá pěkně nasraně.");
            Hide("hospoda");
            Show("HospodaIN");
        }

        void Image5_Click()
        {
            Hide("HospodaIN");
            if (f_3a == 1)
            {
                Show("hospoda");
                if (f_3a == 1) { Say("Vyšel jsi před hospodu"); }
            }
            if (f_3a == 0)
            {
                Show("policie");
                if (f_3a == 0)
                {
                    Hide("inventář");
                    if (f_3a == 0)
                    {
                        Hide("lahev");
                        if (f_3a == 0) { Say("Tak tohle se ti moc nevydařilo - lidi přivolali policie a ta tě zatkla. Vypadá to, že už se svýmu šéfovi nepomstíš. Tohle je tvůj konec!"); }
                    }
                }
            }
        }

        void Image7_Click()
        {
            Say("Ještě nikdy jsi neviděl tak výstižnou karikaturu tvého obličeje");
        }

        void Image7_DragDrop(Control src)
        {
            if (src == C("klíč")) { Say("Tahle kunda je nakreslená, zkus vodemknout nějakou pravou...vole!"); Show("surmaj"); Show("vesmír"); Show("icp"); }
        }

        void Image8_Click()
        {
            Hide("ulička");
            Show("Obchod");
            Say("Přišel jsi zpět před obchod");
        }

        void Image9_Click()
        {
            Say("Tohle zlatíčko stojí 15.000Kč, bohužel je na něm cedulka -RESERVÉ-");
        }

        void Josef_Click()
        {
            Say("Josef Stalin. Vypadá dost nasraně");
        }

        void Josef_DragDrop(Control src)
        {
            if (src == C("whiskeyI") && f_46 == 3) { Hide("PoklopSPECIAL"); Show("Tlačítko"); }
            if (src == C("whiskeyI") && f_46 == 2) { f_46 = 3; }
            if (src == C("whiskeyI") && f_46 == 1) { f_46 = 2; }
            if (src == C("whiskeyI") && f_46 == 0) { f_46 = 1; }
            if (src == C("whiskeyI")) { Show("josefI"); Say("To bylo to pravý!"); Hide("Josef"); Hide("whiskeyI"); }
        }

        void josefI_Click()
        {
            Say("Jen si loknul tá whiskey a už je vysmátej!");
        }

        void kamen_Click()
        {
            Hide("kamen");
            Show("Kámen");
            Say("Sebral si kámen, může se hodit");
        }

        void kamen_DragDrop(Control src)
        {
            if (src == C("klíč")) { Say("Klíč na kámen! To je teda masakr! Ty musíš ještě větší mamrd než vypadáš! Jsi ten největší čurák, jakýho jsem kdy viděl! Klíč na kámen.. to je gól! Seš fakt dement, píčo!"); }
        }

        void Koberec_Click()
        {
            Hide("Koberec");
            Show("Poklop");
            Say("Odsunul jsi koberec. Pod ním se skrývá zamčený, dřevěný poklop");
        }

        void kpoklopu_Click()
        {
            Say("Stojíš u takovýho podivnýho koberce");
            Show("Poklopec");
            Hide("Uvnitř");
        }

        void láhev_Click()
        {
            Show("lahev");
            Hide("láhev");
            Say("Sebral si rozbitou lahev");
        }

        void lahev_DblClick()
        {
            Say("Obyčejná láhev od piva, akorát rozbitá. Dala by se využít jako zbraň");
        }

        void leave_Click()
        {
            Hide("Uvnitř");
            Show("vchod");
            Say("Vyšel jsi před dům");
        }

        void nápis_Click()
        {
            Say("Na ceduli čteš: U Dvou Hlav. Připadá ti to jako úplně nejzkurvenější název pro hospodu");
        }

        void obchodGO_Click()
        {
            Show("Obchod");
            Hide("mapa");
            Say("Přišel jsi před obchod, můžeš také zajít do uličky za obchodem");
        }

        void odejít_Click()
        {
            Show("mapa");
            Hide("Obchod");
            Say("Vyber si kam chceš jít");
        }

        void Okno_Click()
        {
            Say("Oknem vidíš zakouřenou místnost v níž banda násosků popíjí zvětralý pivo a u toho mastí mariáš");
        }

        void pas_Click()
        {
            Say("Se zbrojním pasem nepotřebuješ manipulovat, stačí ho mít u sebe.");
        }

        void PenízeI_Click()
        {
            Say("Je to sice docela trapný, ale takovej balík jen tak nepobereš");
        }

        void pistoleI_DragDrop(Control src)
        {
            if (src == C("tlumič")) { Hide("tlumič"); Hide("pistoleI"); Show("PistoleII"); Say("Tlumič na pistoli parádně pasoval"); }
        }

        void pláž_Click()
        {
            Say("A tohle je konec. Za to že jsi dohrál tuhle hru ti něco prozradím: Zkus si zapnout hru znova a v intru (obrázek továrny) klikni na okno nad rozbitým oknem. Budeš obdařen peněžním obnosem a pokud se budeš snažit, můžeš objevit tajnou lokaci a dohrát hru jiným způsobem!");
            Hide("pláž");
            Show("konec");
        }

        void Poklop_Click()
        {
            Say("Zamčeno");
        }

        void Poklop_DragDrop(Control src)
        {
            if (src == C("klíč")) { Hide("Poklop"); Hide("klíč"); Show("PenízeI"); Say("Odemknul jsi poklop, uvnitř je obrovské množství peněz"); }
        }

        void PoklopSPECIAL_Click()
        {
            Say("Podivný poklop - cosi podivného skrývá");
        }

        void prodavač_Click()
        {
            Say("PRODAVAČ: Nezkoušej mě nasrat!");
        }

        void ProdavačDEATH_Click()
        {
            Say("Jen tam tak leží..mrtev");
        }

        void ProdavačLOOK_Click()
        {
            Say("Je pořádně vytočenej, ani si nevšimnul, že si přišel");
        }

        void rukaviceI_Click()
        {
            Say("To že máš rukavice v inventáři znamená, že je máš nasazené");
        }

        void skrytoš_Click()
        {
            Say("Všimnul sis kamery skryté v kytce. Je to štěstí, protože jinak by si měl asi smůlu");
        }

        void skrytoš_DragDrop(Control src)
        {
            if (src == C("kleštěI")) { Say("Zneškodnil si skrytou kameru"); Hide("skrytoš"); }
        }

        void surmaj_Click()
        {
            Say("CHCÍPNI KURVO SURMAJSKÁ...... HA HA HA HA.... RUMBURK CITY RAPRESSENT ....HA....MY NAME IS MARTY, BIATCH! WRITE ME AN EMAIL YOU FUCKER! m.pohl@worldonline.cz");
        }

        void šéf_Click()
        {
            Say("Spokojeně zařezává. Agresivita roste");
        }

        void šéf_DragDrop(Control src)
        {
            if (src == C("pistoleI")) { Show("šéfGUN"); Say("Napálil si ro přímo do voka. Byla to docela rána"); f_44 = 2; snd = "Shoot.wav"; PlaySound(snd); }
            if (src == C("PistoleII")) { Show("šéfGUN"); Say("Pěkne si ho střelil přímo do oka. Ten tlumič tlumí slušně!"); f_44 = 1; snd = "ShootTl.wav"; PlaySound(snd); }
            if (src == C("BrokovniceI")) { Show("šéfSHOTGUN"); Say("Prásk! Hlava se mu rozprskla po polštáři! To byla ale rána"); f_44 = 2; snd = "Shoot.wav"; PlaySound(snd); }
        }

        void šéfGUN_Click()
        {
            if (V("klíč")) { Say("Už u sebe nic nemá"); }
            if (!V("klíč")) { Say("Našel jsi u něj klíček"); Show("klíč"); }
        }

        void šéfSHOTGUN_Click()
        {
            if (V("klíč")) { Say("Už u sebe nic nemá"); }
            if (!V("klíč")) { Say("Našel jsi u něj klíček"); Show("klíč"); }
        }

        void Tlačítko_Click()
        {
            Show("výbuch");
            Hide("tajnámístnost");
            Say("Vyhodil jsi do povětří Washington, Amerika zaútočila na Rusko a do sporu se přidaly i ostatní státy. Strhla se 3. světová -atomová- válka. Jen málo lidí přežilo - v krytech. Celý svět zamořený... (pokračování ve hře Fallout). KLIKNI NA OBRÁZEK");
            Hide("inventář");
            Hide("lahev");
        }

        void tma_Click()
        {
            Say("Za zdí vidíš...respektive nic nevidíš. Potřebuješ světlo, nevíš co je za zdí. Mohl by si třeba na něco spadnout...");
        }

        void tma_DragDrop(Control src)
        {
            if (src == C("zápalky")) { Say("Zápalky jsou trapný"); }
            if (src == C("baterka") && f_3e == 1) { Hide("tma"); Say("Teď už tam můžeš vniknout bez problémů"); Hide("baterka"); }
        }

        void tulák_DragDrop(Control src)
        {
            if (src == C("lahev")) { Say("Ubodal jsi tuláka"); Hide("tulák"); Show("tulákubodán"); snd = "bum.wav"; PlaySound(snd); }
            if (src == C("PivoI")) { Say("TUlÁK: Jé, díky moc! Nemám co bych ti za to dal, ale alespoň ti povím kde je v tomhle měste nově otevřenej obchod se zbraněma! (řekl ti kudy se tam dostaneš)"); Hide("PivoI"); Hide("skrývač"); f_48 = 1; }
            if (src == C("absinthI")) { Say("TUlÁK: Páni, ty seš ale štědrej! Víš co, vem si tenhle tlumič, já už ho nebudu potřebovat."); Show("tlumič"); Hide("absinthI"); }
            if (src == C("pistoleI")) { Say("Rozhodl ses, že zbytečně nebudeš plýtvat střelivem"); }
            if (src == C("PistoleII")) { Say("Rozhodl ses, že zbytečně nebudeš plýtvat střelivem"); }
            if (src == C("BrokovniceI")) { Say("Rozhodl ses, že zbytečně nebudeš plýtvat střelivem"); }
            if (src == C("klíč")) { Say("You had a lotta dick, had a lotta dick, I had a lotta time, had a lotta time, you had a lotta dick Chasey, but you ain´t had mine!"); }
        }

        void typ_Click()
        {
            Say("Vidíš divnýho týpka, úpěnlivě si prohlíží malby na zdech.");
        }

        void typ_DragDrop(Control src)
        {
            if (src == C("lahev")) { Say("Lahví si ho jenom poranil a když došlo na pěstní souboj, ukázalo se že je silnější než ty"); Hide("ulička"); Hide("inventář"); Hide("lahev"); }
            if (src == C("Kámen")) { Hide("typ"); Show("TypMRTVEJ"); Say("Kamenem si ho udeřil pěkně do hlavy, už se asi nezvedne"); snd = "bum2.wav"; PlaySound(snd); }
        }

        void TypMRTVEJ_Click()
        {
            if (V("pas")) { Say("Ten chudák už u sebe nic víc nemá!"); }
            if (!V("pas")) { Show("baterka"); Say("Prohledal jsi toho týpka a našel jsi u něj nefunkční baterku a zbrojní pas (je to docela podivnost když u sebe nemá zbraň)"); Show("pas"); }
        }

        void uliceGO_Click()
        {
            Say("Přišel jsi na ulici");
            Show("ulice");
            Hide("mapa");
        }

        void vejít_Click()
        {
            Hide("vchod");
            Show("Uvnitř");
            Say("Vešel jsi dovnitř domu, je to tam docela luxus a nóbl. Všude jsou samý kytky, obrazy a zrcadla");
        }

        void vesmír_Click()
        {
            Say("Tyhle čáry sem napsali oni! Mimozemšťany! Sledujou nás, věděj vo nás, vláda o nich taky ví, ale neche nám nic říct! A co pyramidy? To postavili mimozemšťani! Maj dokonce orbitální stanice kolem naší matičky Země!!!");
        }

        void výbuch_Click()
        {
            Show("konec");
            Hide("výbuch");
            Say("A tohle je už opravdu konec. Už žádný jiný triky :-). Dyžtak se mi vozvi, jestli tě ta hra zaujala, jinak FUCK OFF !!!");
        }

        void výloha_Click()
        {
            if (!V("sklo1")) { Say("Úplně obyčejná výloha, je v ní cedule na který stojí: Otevřeno 24 hodin denně. To znamená, že maj otevřeno i teď."); }
            if (V("sklo1")) { Say("Rozbitá výloha zřejmě prodavače dost nasrala, zaujatě si jí prohlíží"); }
        }

        void zápalky_Click()
        {
            Say("Sebral jsi krabičku zápalek, vypadá že je úplně plná");
            Hide("zápalky");
            Show("zápalkyI");
        }

        void Žena_Click()
        {
            Say("Tohle je tvoje bejvalka. Kurva. Má na uších sluchátka, protože šéf hrozně chrápe. Bylo by dobré nejdřív zabít jeho. Ona nic neuslyší");
        }

        void Žena_DragDrop(Control src)
        {
            if (src == C("pistoleI")) { Show("ženaGUN"); Say("Střelils jí přímo mezi voči. Docela šlupa!"); f_44 = 2; snd = "Shoot.wav"; PlaySound(snd); }
            if (src == C("PistoleII")) { Show("ženaGUN"); Say("Trefil ses přímo mezi voči! Tlumič tlumí"); f_44 = 1; snd = "ShootTl.wav"; PlaySound(snd); }
            if (src == C("BrokovniceI")) { Show("ženaSHOTGUN"); Say("To byla ďaha! Hlava jí rupla jak meloun"); f_44 = 2; snd = "Shoot.wav"; PlaySound(snd); }
        }

        void ženaGUN_Click()
        {
            Say("Je mrtvá, co bys chtěl víc!");
        }
    }
}