#!/usr/bin/env python3
"""Generates the C# sources of the port from the recovered data.

  GameForm.Generated.cs  <- recovered/decomp/logic.txt (handlers that decompiled cleanly)
  *.cs                   <- *.cs.in, with every T("prefix") replaced by the full
                            string literal read from the original executable
  Assets/                <- layout, images, icons, sounds
"""
import sys, re, json, struct, os, shutil, glob
ROOT = os.path.dirname(os.path.abspath(__file__)); ZNK = os.path.dirname(ROOT); REC = os.path.join(ZNK, 'recovered')
exe = open(glob.glob(os.path.join(ZNK, '*.exe'))[0], 'rb').read()

# ---- string literals of the original (length-prefixed UTF-16)
lits = []
for o in range(0x38000, 0x3f000, 4):
    n = struct.unpack_from('<I', exe, o - 4)[0]
    if 0 < n < 4000 and n % 2 == 0 and exe[o + n:o + n + 2] == b'\0\0':
        try: t = exe[o:o + n].decode('utf-16le')
        except UnicodeDecodeError: continue
        if all((c >= ' ' and c != '\x7f' and ord(c) < 0x2100) or c in '\r\n\t' for c in t): lits.append(t)
lits = sorted(set(lits))
cs = lambda s: json.dumps(s, ensure_ascii=False)

def strip_blank_frames(ico):
    """Drops icon images that were never drawn (32-bit, every pixel zero).

    The original icons carry an empty 48x48 frame next to the real 32x32 one,
    and Explorer and most viewers pick the empty one and show a black square.
    """
    reserved, kind, count = struct.unpack_from('<HHH', ico, 0)
    if kind != 1: return ico
    keep = []
    for i in range(count):
        entry = ico[6 + 16 * i:22 + 16 * i]
        size, off = struct.unpack_from('<II', entry, 8)
        img = ico[off:off + size]
        header, bpp = struct.unpack_from('<I', img, 0)[0], struct.unpack_from('<H', img, 14)[0]
        w, h = struct.unpack_from('<i', img, 4)[0], abs(struct.unpack_from('<i', img, 8)[0]) // 2
        pixels = img[header:header + w * 4 * h]
        if bpp == 32 and not any(pixels): continue
        keep.append((entry, img))
    if not keep or len(keep) == count: return ico
    out, off = struct.pack('<HHH', 0, 1, len(keep)), 6 + 16 * len(keep)
    for entry, img in keep:
        out += entry[:12] + struct.pack('<I', off); off += len(img)
    return out + b''.join(img for entry, img in keep)

def resolve(text, fname):
    def rep(m):
        p = json.loads('"%s"' % m.group(1))
        hit = [s for s in lits if s == p] or [s for s in lits if s.startswith(p)]
        if len(hit) != 1: sys.exit('%s: T("%s") matches %d strings: %r' % (fname, p, len(hit), hit[:4]))
        return cs(hit[0])
    return re.sub(r'\bT\("((?:[^"\\]|\\.)*)"\)', rep, text)

hand_src = open(os.path.join(ROOT, 'GameForm.Hand.cs.in'), encoding='utf-8').read()
HAND = set(re.findall(r'^    void (\w+)\(', hand_src, re.M))

# ---- translate the clean handlers
STR = r'"(?:[^"\\]|\\.)*"'
blocks = re.split(r'(?=^### )', open(os.path.join(REC, 'decomp', 'logic.txt'), encoding='utf-8').read(), flags=re.M)[1:]
out, wire, skipped = [], [], []
for b in blocks:
    form, rest = re.match(r'### (\w+)\.(\S+)', b).groups()
    if form != 'Form2': continue
    name = rest; ctl, ev = name.rsplit('_', 1)
    if ctl not in ('Form', 'Timer1'):
        wire.append('        On%s(%s, %s);' % (ev, cs(ctl), name))
    if name in HAND: continue
    body, _, tail = b.partition('// STRINGS NOT SHOWN')
    wavs = re.findall(r'"([^"]+\.wav)"', tail)
    body = body[body.find('{'):body.rfind('}') + 1]
    body = re.sub(r'__vbaVarCopy\(\);', lambda m: 'snd = %s;' % cs(wavs.pop(0)), body)
    strs = []
    def stash(m): strs.append(m.group(0)); return '\x00%d\x00' % (len(strs) - 1)
    t = re.sub(STR, stash, body)
    t = re.sub(r'(\w+)\.Visible\(0\);', r'Hide("\1");', t)
    t = re.sub(r'(\w+)\.Visible\(True\);', r'Show("\1");', t)
    t = re.sub(r'text\.Caption\((\x00\d+\x00)\);', r'Say(\1);', t)
    t = re.sub(r'(\w+)\.Caption\((\x00\d+\x00)\);', r'SetText("\1", \2);', t)
    t = re.sub(r'(\w+)\.ToolTip\((\x00\d+\x00)\);', r'Tip("\1", \2);', t)
    t = re.sub(r'Source == (\w+)', r'src == C("\1")', t)
    t = re.sub(r'!(\w+)\.Visible\b', r'!V("\1")', t)
    t = re.sub(r'(?<![\w"])(\w+)\.Visible\b', r'V("\1")', t)
    t = re.sub(r'\(short\)F_(\w+)', r'f_\1', t)
    t = re.sub(r'(\d+)\.0\b', r'\1', t)
    t = re.sub(r'\x00(\d+)\x00', lambda m: strs[int(m.group(1))], t)
    if wavs or re.search(r'piVar|__vba|fVar|local_|uVar|sVar|bVar|iVar|F_\w+|code \*\*|\.m[0-9a-f]+\(|return', re.sub(STR, '""', t)):
        skipped.append(name); continue
    lines = [l.strip() for l in t.split('\n') if l.strip()]
    ind, res = 1, []
    for l in lines[1:-1]:
        if l.startswith('}'): ind -= 1
        res.append('    ' * (ind + 1) + l)
        if l.endswith('{'): ind += 1
    sig = 'void %s(%s)' % (name, 'Control src' if ev == 'DragDrop' else '')
    out.append('    %s\n    {\n%s\n    }' % (sig, '\n'.join(res)))
if skipped: sys.exit('not clean and not hand-written: %s' % skipped)

gen = '''namespace ZNK;

// GENERATED by gen.py from the decompiled handlers of the original Form2.
// Statement order is exactly the original's. Do not edit; edit gen.py or
// move a handler into GameForm.Hand.cs.in instead.
sealed partial class GameForm
{
    void WireEvents()
    {
%s
    }

%s
}
''' % ('\n'.join(wire), '\n\n'.join(out))
open(os.path.join(ROOT, 'GameForm.Generated.cs'), 'w', encoding='utf-8', newline='\n').write(gen)
for src in glob.glob(os.path.join(ROOT, '*.cs.in')):
    open(src[:-3], 'w', encoding='utf-8', newline='\n').write(resolve(open(src, encoding='utf-8').read(), os.path.basename(src)))

# ---- assets
A = os.path.join(ROOT, 'Assets'); lay = json.load(open(os.path.join(REC, 'layout.json'), encoding='utf-8'))
used = {c.get(k) for f in lay.values() for c in f for k in ('picture', 'mouseIcon', 'dragIcon')} - {None}
for u in used:
    dst = os.path.join(A, 'images', u); os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copyfile(os.path.join(REC, 'images', u), dst)
    if u.endswith('.ico'): open(dst, 'wb').write(strip_blank_frames(open(os.path.join(REC, 'images', u), 'rb').read()))
shutil.copyfile(os.path.join(REC, 'layout.json'), os.path.join(A, 'layout.json'))
os.makedirs(os.path.join(A, 'sounds'), exist_ok=True)
for w in glob.glob(os.path.join(ZNK, '*.wav')): shutil.copyfile(w, os.path.join(A, 'sounds', os.path.basename(w)))
# ---- app icon: the form's own icon from the original
o = exe.index(b'\x00\x22\x00\x23', 0x1a68) + 4
n = struct.unpack_from('<I', exe, o + 8)[0]
os.makedirs(os.path.join(A, 'images', 'icons'), exist_ok=True); os.makedirs(os.path.join(A, 'icons'), exist_ok=True)
open(os.path.join(A, 'icons', 'app.ico'), 'wb').write(strip_blank_frames(exe[o + 12:o + 12 + n]))

# ---- every control the code names must exist in the layout
bad = []
for fname, form in (('IntroForm.cs', 'Form1'), ('GameForm.Generated.cs', 'Form2'), ('GameForm.Hand.cs', 'Form2')):
    names = {(c['name'] + ('(%d)' % c['index'] if 'index' in c else '')).lower() for c in lay[form]}
    src = open(os.path.join(ROOT, fname), encoding='utf-8').read()
    for fn, n in re.findall(r'\b(C|V|Show|Hide|Tip|SetText|GetText|OnClick|OnDblClick|OnDragDrop)\("([^"]+)"', src):
        if n.lower() not in names: bad.append((fname, fn, n))
    for n in re.findall(r'timers\["([^"]+)"\]', src):
        if n.lower() not in names: bad.append((fname, 'timer', n))
if bad: sys.exit('unknown controls referenced: %r' % sorted(set(bad)))
print('generated %d handlers, %d hand-written, %d events wired, %d strings, %d asset files' % (len(out), len(HAND), len(wire), len(lits), len(used)))
