<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>ZivotNeniKrasny</AssemblyName>
    <RootNamespace>ZNK</RootNamespace>
    <ApplicationIcon>Assets\icons\app.ico</ApplicationIcon>
    <NoWarn>CS8981;IDE1006</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Assets\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
