<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>ZivotNeniKrasny</AssemblyName>
    <RootNamespace>ZNK</RootNamespace>
    <ApplicationIcon>Assets\icons\app.ico</ApplicationIcon>
    <NoWarn>CS8981;IDE1006</NoWarn>
    <StartupObject>ZNK.Program</StartupObject>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Assets\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="10.0.12" />
  </ItemGroup>
</Project>
